### ISSUE TITLE
Please support array of arrays as result option

### ISSUE THREAD

**Issue by BerndWessels** [chilltemp/tedious-promises#1]
Hi
Could you add an option that returns the result as an array of arrays?

So basically the result should be an array of rows, and each row is an array of columns.

```
result =
{
    columns: ['col_1', 'col_2'],
    rows:
    [
        [ 'row1_col1', 'row1_col2' ],
        [ 'row2_col1', 'row2_col2' ]
    ]
};
```

The main reason is to reduce the amount of data I have to transfer to my client and repeating the column names over and over again is such a waste.

It also matches the CSV format much better which is often used with charts like D3.

Thanks
Bernd

**Comment by chilltemp** [comment]
This sounds reasonable, and should be an easy option to implement.  I'll take a look when I'm coding on personal time next.  I also open to pull requests.  Just let me know if you intend to, that way we don't duplicate our work.

**Comment by BerndWessels** [comment]
@chilltemp Thank you so much for considering.
I would love to present you with a PR but unfortunately haven't had time to study the code yet to do a good job on that.
Cheers
Bernd

**Comment by chilltemp** [comment]
I've implemented most of your request.  What I did will return the rows with arrays of values, but without the column names header.

It's in the develop branch.   I've got 1 more ticket to complete before I do a npmjs release.

**Comment by BerndWessels** [comment]
@chilltemp Awesome, thanks. Looking forward to it.

**Comment by BerndWessels** [comment]
@chilltemp Hi, are you going to publish this to npm soon?

**Comment by chilltemp** [comment]
Hopefully sometime next week, but I'm tracking down a minor bug or 2 with this version.  You are welcome to use this version.  You can bypass npmjs and use this beta version directly if you'd like.  None of the bugs so far have been critical.  

Update your package.json with this if you want to use a version the beta:
git+https://github.com/chilltemp/tedious-promises.git#v0.3.3

Beta v0.3.4 will be available in a day or 2.

**Comment by BerndWessels** [comment]
@chilltemp Thanks, will do that. Looking forward to the release - great work.

**Comment by chilltemp** [comment]
Released

**Comment by BerndWessels** [comment]
@chilltemp awesome, love it, thank you.
