### ISSUE TITLE
setPromiseLibrary throwing exception

### ISSUE THREAD

**Issue by leemm** [chilltemp/tedious-promises#10]
I'm trying to switch to es6 promises but some reason setPromiseLibrary doesn't exist.  Haven't checked the other version e.g. tp.sql().setPromiseLibrary.

```
tediousPromises.setPromiseLibrary('es6');

> TypeError: tediousPromises.setPromiseLibrary is not a function
```

After a bit of digging around I found out that this function isn't bound to the default instance in src/index.js.  It works if this is added:

```
module.exports.setPromiseLibrary = defaultInstance.setPromiseLibrary.bind(defaultInstance);
```

I need it for one of my projects so I've forked it for now.  Hope you can add in and publish to npm.

Cheers.

**Comment by chilltemp** [comment]
Added.  Feel free to send me PR's for any other fixes / enhancements.  I'm always happy for help.
