### ISSUE TITLE
Add Information about how to retrieve the inserted record

### ISSUE THREAD

**Issue by jeanbauer** [chilltemp/tedious-promises#9]
Something like this would be very helpful for those who wants that auto-generated ID on the callback from the request.

const query = `INSERT INTO Address ( number ) VALUES('${number}'); select @@identity`;

```

tp.setConnectionConfig(config);
return tp.sql(query)
  .execute()
  .then(record => console.log('inserted', record))
  .fail(error => res.status(400).send({ message: error }));
```

**Comment by chilltemp** [comment]
Sample added.
If you `select @@identity as id` you can access it with `record[0].id`
